#!/bin/sh
set -e

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework

setupenvironment
configarchitecture 'amd64' 'i386'

buildsimplenativepackage 'testing' 'amd64,i386' '0.8.15' 'stable'
buildsimplenativepackage 'testing2' 'amd64,i386' '0.8.15' 'stable'
setupaptarchive 

# install native
exec 3> apt-progress.log
testsuccess aptget install testing -y -o APT::Status-Fd=3

# and compare
testequal "dlstatus:1:0:Retrieving file 1 of 1
dlstatus:1:0:Retrieving file 1 of 1
pmstatus:dpkg-exec:0:Running dpkg
pmstatus:testing:0:Installing testing
pmstatus:testing:amd64:20:Preparing testing:amd64
pmstatus:testing:amd64:40:Unpacking testing:amd64
pmstatus:testing:amd64:60:Preparing to configure testing:amd64
pmstatus:dpkg-exec:60:Running dpkg
pmstatus:testing:60:Configuring testing
pmstatus:testing:amd64:80:Configuring testing:amd64
pmstatus:testing:amd64:100:Installed testing:amd64" cat apt-progress.log

# install non-native and ensure we get proper progress info
exec 3> apt-progress2.log
testsuccess aptget install testing2:i386 -y -o APT::Status-Fd=3

# and compare
testequal "dlstatus:1:0:Retrieving file 1 of 1
dlstatus:1:0:Retrieving file 1 of 1
pmstatus:dpkg-exec:0:Running dpkg
pmstatus:testing2:0:Installing testing2
pmstatus:testing2:i386:20:Preparing testing2:i386
pmstatus:testing2:i386:40:Unpacking testing2:i386
pmstatus:testing2:i386:60:Preparing to configure testing2:i386
pmstatus:dpkg-exec:60:Running dpkg
pmstatus:testing2:60:Configuring testing2
pmstatus:testing2:i386:80:Configuring testing2:i386
pmstatus:testing2:i386:100:Installed testing2:i386" cat apt-progress2.log

rm -f apt-progress*.log