#!/bin/sh
set -e

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework

setupenvironment
configarchitecture "i386"
changetowebserver

# setup env
mkdir -p var/lib/apt/keyrings
mkdir -p usr/share/keyrings

# install the fake master keyring
install -m0644 keys/test-master-keyring.pub usr/share/keyrings
echo "APT::Key::MasterKeyring \"${TMPWORKINGDIRECTORY}/usr/share/keyrings/test-master-keyring.pub\";" >> ./aptconfig.conf

# setup archive-keyring 
mkdir -p aptarchive/ubuntu/project
install -m0644 keys/test-archive-keyring.pub aptarchive/ubuntu/project/
# sign the test-archive-keyring.pub with the master-key
gpg  --no-default-keyring --secret-keyring keys/test-master-keyring.sec --keyring  keys/test-master-keyring.pub --default-key "test-master@example.com"  --sign --output aptarchive/ubuntu/project/test-archive-keyring.pub.sig aptarchive/ubuntu/project/test-archive-keyring.pub

# setup the right vars
echo "APT::Key::ArchiveKeyringURI \"http://localhost:${APTHTTPPORT}/ubuntu/project/test-archive-keyring.pub.sig\";" >> ./aptconfig.conf
echo 'APT::Key::Net-Update-Enabled "1";' >> ./aptconfig.conf

# keyring empty
aptkey list | grep '^pub' > aptkey.list
testfileequal ./aptkey.list 'pub   2048R/DBAC8DAE 2010-08-18'

# test against the "real" webserver
testsuccess aptkey --fakeroot net-update

# keyring contains archive key
aptkey list | grep '^pub' > aptkey.list
testfileequal ./aptkey.list 'pub   1024R/F68C85A3 2013-12-19
pub   2048R/DBAC8DAE 2010-08-18'

# now try a different one
# setup archive-keyring 
mkdir -p aptarchive/ubuntu/project
install -m0644 keys/marvinparanoid.pub aptarchive/ubuntu/project/
gpg  --no-default-keyring --secret-keyring ./keys/marvinparanoid.sec --keyring ./keys/marvinparanoid.pub --default-key marvin@example.org --sign --output aptarchive/ubuntu/project/marvinparanoid.pub.sig aptarchive/ubuntu/project/marvinparanoid.pub
echo "APT::Key::ArchiveKeyringURI \"http://localhost:${APTHTTPPORT}/ubuntu/project/marvinparanoid.pub.sig\";" >> ./aptconfig.conf
echo 'APT::Key::Net-Update-Enabled "1";' >> ./aptconfig.conf

# test against the "real" webserver
testfailure aptkey --fakeroot net-update

# keyring unchanged
aptkey list | grep '^pub' > aptkey.list
testfileequal ./aptkey.list 'pub   1024R/F68C85A3 2013-12-19
pub   2048R/DBAC8DAE 2010-08-18'
