#!/bin/sh
set -e

TESTDIR=$(readlink -f $(dirname $0))
. $TESTDIR/framework

setupenvironment
configarchitecture "i386"

echo 'APT::Sources::Use-Deb822 "1";' > rootdir/etc/apt/apt.conf.d/deb822

cat > rootdir/etc/apt/sources.list <<EOF
deb [arch=amd64] http://ftp.debian.org/debian unstable main contrib
deb-src http://ftp.debian.org/debian unstable main
EOF

testequal "deb [arch=amd64] http://ftp.debian.org/debian/ unstable main contrib
deb-src http://ftp.debian.org/debian/ unstable main" aptsources list

cat > rootdir/etc/apt/sources.list <<EOF
Types: deb deb-src
URIs: http://ftp.debian.org/debian/
Suites: unstable
Sections: main contrib
Architectures-Add: amd64
Architectures-Remove: armhf
EOF

testequal "deb [arch+=amd64,arch-=armhf] http://ftp.debian.org/debian/ unstable main contrib
deb-src [arch+=amd64,arch-=armhf] http://ftp.debian.org/debian/ unstable main contrib" aptsources list
